### ISSUE TITLE
Reactive select items on a multi gets an "Session is currently connecting to database"

### ISSUE THREAD

**Issue by tiagomistral** [quarkusio/quarkus-quickstarts#1018]
Hello,

I made a small change on **hibernate-reactive-panache-quickstart** and I cannot do multiple simple queries on a Mutiny.multi iteration:

Replace  FruitResource#get
    
    @Inject
    Mutiny.Session mutinySession;
    
    @GET
    public Uni<List<Fruit>> get() {
        //return Fruit.listAll(Sort.by("name"));
        return Multi.createFrom().items(1l,2l,3l,4l,5l,6l,7l,8l,2l,3l,4l,5l,6l,7l,8l,2l,3l,4l,5l,6l,7l,8l).onItem()
                .<Fruit>transformToUniAndMerge(id -> 
                mutinySession.find(Fruit.class, id)
                    ).collect().asList();
    }

when access http://localhost:8080/fruits

>  2021-12-15 15:57:27,537 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-15) HR000057: Failed to execute statement [$1select fruit0_.id as id1_0_0_, fruit0_.name as name2_0_0_ from Fruit fruit0_ where fruit0_.id=$1]: $2could not load an entity: [org.acme.hibernate.orm.panache.Fruit#2]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: HR000061: Session is currently connecting to database
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1099)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.hibernate.reactive.loader.ReactiveLoader.doReactiveQueryAndInitializeNonLazyCollections(ReactiveLoader.java:75)
	at org.hibernate.reactive.loader.ReactiveLoader.doReactiveQueryAndInitializeNonLazyCollections(ReactiveLoader.java:44)
	at org.hibernate.reactive.loader.entity.impl.ReactivePlanEntityLoader.load(ReactivePlanEntityLoader.java:243)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.reactiveLoad(ReactiveAbstractEntityPersister.java:951)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.reactiveLoad(ReactiveAbstractEntityPersister.java:940)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.loadFromDatasource(DefaultReactiveLoadEventListener.java:663)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.doLoad(DefaultReactiveLoadEventListener.java:626)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.load(DefaultReactiveLoadEventListener.java:289)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.proxyOrLoad(DefaultReactiveLoadEventListener.java:405)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.doOnLoad(DefaultReactiveLoadEventListener.java:210)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.lambda$reactiveOnLoad$1(DefaultReactiveLoadEventListener.java:140)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.reactiveOnLoad(DefaultReactiveLoadEventListener.java:139)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.lambda$fireEventOnEachListener$1(EventListenerGroupImpl.java:148)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:148)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.fireLoadNoChecks(ReactiveSessionImpl.java:1084)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.fireLoad(ReactiveSessionImpl.java:1077)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.access$200(ReactiveSessionImpl.java:120)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl$ReactiveIdentifierLoadAccessImpl.doLoad(ReactiveSessionImpl.java:1230)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl$ReactiveIdentifierLoadAccessImpl.lambda$load$5(ReactiveSessionImpl.java:1213)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl$ReactiveIdentifierLoadAccessImpl.perform(ReactiveSessionImpl.java:1180)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl$ReactiveIdentifierLoadAccessImpl.load(ReactiveSessionImpl.java:1213)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.reactiveFind(ReactiveSessionImpl.java:1020)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl.lambda$find$3(MutinySessionImpl.java:109)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at org.hibernate.reactive.context.impl.VertxContext.execute(VertxContext.java:69)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.subscribe(UniRunSubscribeOn.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:63)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:591)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:24)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:156)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:191)
	at io.smallrye.mutiny.operators.multi.builders.CollectionBasedMulti$CollectionSubscription.followRequests(CollectionBasedMulti.java:90)
	at io.smallrye.mutiny.operators.multi.builders.CollectionBasedMulti$CollectionSubscription.request(CollectionBasedMulti.java:69)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onSubscribe(MultiFlatMapOp.java:163)
	at io.smallrye.mutiny.operators.multi.builders.CollectionBasedMulti.subscribe(CollectionBasedMulti.java:37)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:40)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp.subscribe(MultiFlatMapOp.java:54)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:69)
	at io.smallrye.mutiny.operators.multi.MultiCollectorOp.subscribe(MultiCollectorOp.java:55)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:40)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromPublisher$PublisherSubscriber.forward(UniCreateFromPublisher.java:42)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromPublisher$PublisherSubscriber.access$100(UniCreateFromPublisher.java:30)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromPublisher.subscribe(UniCreateFromPublisher.java:26)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:17)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:154)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:117)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:217)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: HR000061: Session is currently connecting to database
	at org.hibernate.reactive.pool.impl.ProxyConnection.withConnection(ProxyConnection.java:66)
	at org.hibernate.reactive.pool.impl.ProxyConnection.selectJdbc(ProxyConnection.java:129)
	at org.hibernate.reactive.loader.ReactiveLoader.executeReactiveQueryStatement(ReactiveLoader.java:128)
	at org.hibernate.reactive.loader.ReactiveLoader.doReactiveQueryAndInitializeNonLazyCollections(ReactiveLoader.java:69)
	... 79 more

**Comment by tiagomistral** [comment]
Demo:
[hibernate-reactive-panache-quickstart.zip](https://github.com/quarkusio/quarkus-quickstarts/files/7720921/hibernate-reactive-panache-quickstart.zip)

Just download and run `mvn Quarkus:dev`

**Comment by tiagomistral** [comment]
I found out that if we change from `transformToUniAndMerge` to `transformToUniAndConcatenate` it works :)
