### ISSUE TITLE
Quarkus ignores CTRL+C signal after Kafka topic exception

### ISSUE THREAD

**Issue by evanshortiss** [quarkusio/quarkus-quickstarts#1065]
I mistakenly misconfigured a connector and ran into this issue. It's minor, but a bit annoying.

The following is printed to stdout, then the `UNKNOWN_TOPIC_OR_PARTITION` is continuously printed until I manually sent a kill signal to the process:

```
2022-02-21 11:09:42,497 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-generated-prices) [Producer clientId=kafka-producer-generated-prices] Error while fetching metadata with correlation id 15 : {generated-prices=UNKNOWN_TOPIC_OR_PARTITION}
2022-02-21 11:09:42,600 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-20) HTTP Request to /prices/usd/stream failed, error id: a43b82c3-6f64-4839-8350-5f578e648a2c-1: java.lang.IllegalStateException: cacheDir has been removed. FileResolver is closing?
	at io.vertx.core.file.impl.FileCache.getCacheDir(FileCache.java:235)
	at io.vertx.core.file.impl.FileCache.relativize(FileCache.java:161)
	at io.vertx.core.file.impl.FileResolverImpl.resolveFile(FileResolverImpl.java:124)
	at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:770)
2022-02-21 11:09:42,681 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-generated-prices) [Producer clientId=kafka-producer-generated-prices] Error while fetching metadata with correlation id 16 : {generated-prices=UNKNOWN_TOPIC_OR_PARTITION}
```

A little while later it printed this log, then returned to printing `UNKNOWN_TOPIC_OR_PARTITION`:

```
2022-02-21 11:09:58,296 WARNING [org.aes.rea.tty.ter.TerminalConnection] (Aesh InputStream Reader) Failed while reading, exiting: java.io.IOException: Input/output error
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:254)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:214)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The following was in my `application.properties`:

```
// Generate and write data to this topic
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=usd-prices
mp.messaging.outgoing.generated-price.value.serializer=org.apache.kafka.common.serialization.StringSerializer

// Used to read generated data back into the application
mp.messaging.incoming.usd-prices.connector=smallrye-kafka
mp.messaging.incoming.usd-prices.topic=usd-prices
mp.messaging.incoming.usd-prices.value.serializer=org.apache.kafka.common.serialization.StringSerializer
```

My Java source mistakenly referenced `generated-prices` instead of `generated-price`:

```java
@Outgoing("generated-prices")
```

I then attempted to access a SSE stream:

```java
@Inject
@Channel("usd-prices")
Publisher<String> usdPrices;

@GET
@Path("/usd/stream")
@Produces(MediaType.SERVER_SENT_EVENTS) // denotes that server side events (SSE) will be produced
public Publisher<String> streamUSD() {
    return usdPrices;
}
```

**Comment by cescoffier** [comment]
The `UNKNOWN_TOPIC_OR_PARTITION` is expected. Kafka retries Integer.MAX_VALUE by default. It will only stop after that (huge) number of attempts or if it reaches some timeout (I don't remember the default, it's a few minutes I think).

The cache dir issue is more annoying. I would need to know what's trying to read/write to this directory.

**Comment by evanshortiss** [comment]
The issue is the program ignoring SIGINT. The reason I mentioned `UNKNOWN_TOPIC_OR_PARTITION` it that SIGINT is ignored once this error occurs. I can shortren/simplify the description if that would help.

**Comment by cescoffier** [comment]
The retries are executed by the Kafka NetClient which cannot be interrupted (at least last time I checked).

**Comment by evanshortiss** [comment]
The process should still capture and respect the SIGINT, regardless of what an underlying library is doing though right? Maybe not, and developers should just write code to manually capture the signal when using Quarkus?

**Comment by cescoffier** [comment]
I need to check again, but I don't believe we have the hand on it. It's a daemon thread, so it keeps running. Maybe if we send a WakeUpException it can be interrupted.

**Comment by evanshortiss** [comment]
Gotcha. I'm not deeply familiar with Java, so perhaps what I consider to be intuitive behaviour is misaligned with the Java community expectations. But yes, it sounds like the parent should interrupt it

I also appreciate this is not super high priority, so thanks for taking a look 🙂
