### ISSUE TITLE
Hibernate - Entity Manager is not being scoped

### ISSUE THREAD

**Issue by richsanram** [quarkusio/quarkus-quickstarts#125]
I got the next error, with a custom project and also with hibernate-orm-panache-resteasy project, so it's clear that it does not have nothing related to my own code.

At the start of the server, the log shows the next message:
20:41:06,658 INFO  [org.hib.orm.beans] HHH10005002: No explicit CDI BeanManager reference was passed to Hibernate, but CDI is available on the Hibernate ClassLoader.

Then when I call a service using panache methods, i got the next exception:

javax.enterprise.context.ContextNotActiveException: 
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.delegate(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:91)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:276)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:158)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.find(JpaOperations.java:186)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.find(JpaOperations.java:178)

**Comment by richsanram** [comment]
I see now that it's related to an existing issue, about Panache not working with async controllers, using CompletionStage return type and lambdas with CompletableFuture.supplyAsync

**Comment by gsmet** [comment]
Yes, better open an issue in the main project if it's still an issue with 0.13.2. Please include a reproducer. Thanks!

**Comment by FroMage** [comment]
Yes, this is surely related to context propagation. Follow quarkusio/quarkus#467 to check progress.
