### ISSUE TITLE
security-web-authn-quickstart fails with a netty connection refused in localhost/127.0.0.1:32769 

### ISSUE THREAD

**Issue by jcarranzan** [quarkusio/quarkus-quickstarts#1336]
Hi, I am following the Readme steps https://github.com/quarkusio/quarkus-quickstarts/tree/main/security-webauthn-quickstart#readme to execute the security-webauthn-quickstart.

And I got a connection refused in localhost/127.0.0.1:32769 error when I try to register a user with the UI app running pressing the register button.

### Steps to reproduce it
1. In a terminal I type the command:  `docker-compose up` and according the logs is up and running `LOG:  database system is ready to accept connections
`
2. In another terminal I type `mvn compile quarkus:dev`

3. Open a browser with http://localhost:8080 and fill the user textbox on the Register section and press the register button so I got the error response: Registration failed: Error: Internal Server Error and if I go to the detailed response it is a 500 server error with:
`io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:32769
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`
	
It is supposed that the PostgreSQL database starts as a Dev Service and the app is up  but with some WARN logs as : 

 `HR000021: DDL command failed [io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:32769]`

The database config also looks good to me : 
`database:
    image: "postgres:10.5"
    container_name: "elytron-security-webauthn-database"
    ports:
      - "5432:5432"`

Maybe I am missing something but should there be a way to map to the correct port 5432  in the application.properties and remove the %prod config?

**Comment by jcarranzan** [comment]
If I executed only `mvn compile quarkus:dev` then Dev Services up the docker containers and everything should be works fine but in the logs :
' Dev Services for default datasource (postgresql) started - container ID is 5cbd87adbbad
2023-10-18 08:40:49,350 INFO  [org.hib.rea.pro.imp.ReactiveIntegrator] (JPA Startup Thread) HR000001: Hibernate Reactive
2023-10-18 08:40:49,722 WARN  [org.hib.rea.pro.ser.ReactiveGenerationTarget] (vert.x-eventloop-thread-0) HR000021: DDL command failed [io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:32785]
2023-10-18 08:40:49,726 WARN  [org.hib.rea.pro.ser.ReactiveGenerationTarget] (vert.x-eventloop-thread-0) HR000021: DDL command failed [io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:32785] '
If I go to the terminal and type `docker ps --all` there are 2 containers like this: 
`CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                     PORTS                     NAMES
5cbd87adbbad        postgres:14                 "docker-entrypoint.s…"   2 minutes ago       Exited (1) 2 minutes ago                             relaxed_tu
c3f34d39df8e        testcontainers/ryuk:0.5.1   "/bin/ryuk"              2 minutes ago       Up 2 minutes               0.0.0.0:32784->8080/tcp   testcontainers-ryuk-1cdc381f-c20c-4e0f-9bc2-369eefb95957
`
And I realized that the port of the application try to access to the port 32785 and the port mapping from one of the container is `32784`
