### ISSUE TITLE
kafka quickstart failed when generate a native image with quarkus-agroal

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus-quickstarts#201]
Version: 0.15.0
if pom.xml add below artifactId
```xml
                <dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-agroal</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-narayana-jta</artifactId>
		</dependency>
```

Goals: "clean package -Pnative"
raise error:

```java
...$ ./kafka-quickstart-1.0-SNAPSHOT-runner
19:07:38.119 INFO  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:100,initializeAndRun()] Deployment done... start processing
19:07:38.120 INFO  [main] [io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory:94,initialize()] Stream manager initializing...
19:07:38.122 ERROR [main] [io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory:103,initialize()] Unable to create the publisher or subscriber during initialization: java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
	at io.smallrye.config.ImplicitConverters$StaticMethodConverter.convert(ImplicitConverters.java:99)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:76)
	at io.smallrye.reactive.messaging.impl.ConnectorConfig.getValue(ConnectorConfig.java:57)
	at io.smallrye.reactive.messaging.spi.ConfigurationHelper.asJsonObject(ConfigurationHelper.java:51)
	at io.smallrye.reactive.messaging.kafka.KafkaSource.<init>(KafkaSource.java:35)
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider.getPublisherBuilder(KafkaMessagingProvider.java:40)
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider_ClientProxy.getPublisherBuilder(Unknown Source)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory.createPublisherBuilder(LegacyConfiguredStreamFactory.java:119)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory.lambda$initialize$2(LegacyConfiguredStreamFactory.java:100)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory.initialize(LegacyConfiguredStreamFactory.java:100)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory_ClientProxy.initialize(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:102)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:18)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(Unknown Source)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:244)
	at io.quarkus.arc.EventImpl.fire(EventImpl.java:85)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:39)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate.handleLifecycleEvents(ArcDeploymentTemplate.java:115)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent19.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:100)
	at io.quarkus.runtime.Application.run(Application.java:212)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.smallrye.config.ImplicitConverters$StaticMethodConverter.convert(ImplicitConverters.java:97)
	... 28 more
Caused by: java.lang.NumberFormatException: For input string: "org.apache.kafka.common.serialization.StringDeserializer"
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	... 30 more

19:07:38.122 INFO  [main] [io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory:61,<init>()] Found incoming connectors: [class io.smallrye.reactive.messaging.kafka.Kafka]
19:07:38.122 INFO  [main] [io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory:62,<init>()] Found outgoing connectors: [class io.smallrye.reactive.messaging.kafka.Kafka]
19:07:38.122 INFO  [main] [io.smallrye.reactive.messaging.impl.ConfiguredStreamFactory:97,initialize()] Stream manager initializing...
19:07:38.123 INFO  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:104,initializeAndRun()] Initializing mediators
19:07:38.123 INFO  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:157,weaving()] Connecting mediators
19:07:38.123 INFO  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:166,lambda$weaving$6()] Attempt to resolve org.acme.quarkus.sample.PriceConverter2#process
19:07:38.124 WARN  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:192,weaving()] Impossible to bind mediators, some mediators are not connected: [org.acme.quarkus.sample.PriceConverter2#process]
19:07:38.124 WARN  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:196,weaving()] Available publishers: [topic-price]
19:07:38.124 WARN  [main] [io.smallrye.reactive.messaging.extension.MediatorManager:197,weaving()] Available emitters: [topic-price]
19:07:38.124 INFO  [main] [io.quarkus.runtime.Timing:74,printStartupTime()] Quarkus 0.15.0 started in 0.035s. Listening on: http://[::]:8080
19:07:38.124 INFO  [main] [io.quarkus.runtime.Timing:75,printStartupTime()] Installed features: [agroal, cdi, narayana-jta, resteasy, scheduler, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, smallrye-reactive-streams-operators, vertx]
19:07:41.123 INFO  [DefaultQuartzScheduler_Worker-1] 
```

java.lang.NumberFormatException: For input string: "org.apache.kafka.common.serialization.StringDeserializer"

**Comment by cescoffier** [comment]
It has been fixed in `development`.
