### ISSUE TITLE
"address already in use" doesn't fail a compile

### ISSUE THREAD

**Issue by jmtd** [quarkusio/quarkus-quickstarts#24]
When the chosen port is not available to bind to, maven still considers the compile a success. From the  getting-started sub-directory:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.acme:shamrock-quickstart >--------------------
[INFO] Building shamrock-quickstart 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ shamrock-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jon/protean-quickstarts/getting-started/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ shamrock-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/jon/protean-quickstarts/getting-started/target/classes
[INFO] 
[INFO] --- shamrock-maven-plugin:0.6.0:dev (default-cli) @ shamrock-quickstart ---
[ERROR] Port 5005 in use, not starting in debug mode
2019-01-17 13:54:57,123 localhost shamrock-quickstart-dev.jar[25297] INFO  [o.xnio] (main) XNIO version 3.6.5.Final
2019-01-17 13:54:57,158 localhost shamrock-quickstart-dev.jar[25297] INFO  [o.x.nio] (main) XNIO NIO Implementation Version 3.6.5.Final
2019-01-17 13:54:57,242 localhost shamrock-quickstart-dev.jar[25297] INFO  [o.j.threads] (main) JBoss Threads version 3.0.0.Alpha4
Exception in thread "main" java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:249)
	at org.jboss.shamrock.undertow.runtime.UndertowDeploymentTemplate.startUndertowEagerly(UndertowDeploymentTemplate.java:241)
	at org.jboss.shamrock.dev.RuntimeCompilationSetup.setup(RuntimeCompilationSetup.java:64)
	at org.jboss.shamrock.dev.DevModeMain.main(DevModeMain.java:80)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:178)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:303)
	at io.undertow.Undertow.start(Undertow.java:194)
	... 3 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.272 s
[INFO] Finished at: 2019-01-17T13:54:57Z
[INFO] ------------------------------------------------------------------------
```

IMHO this should fail the build.

**Comment by gsmet** [comment]
I think this was fixed by this one: https://github.com/quarkusio/quarkus/pull/1905 . It will be included in the upcoming 0.14.0.
