### ISSUE TITLE
using-vertx QS throws error in native mode 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#265]
using-vertx QS throws error in native mode, app boots, tests are passing ...
run command: `mvn clean verify -Dnative` 

Main message:
Cannot instantiate the MessageCodec class io.quarkus.vertx.runtime.GenericMessageCodec: java.lang.InstantiationException: Type `io.quarkus.vertx.runtime.GenericMessageCodec` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
 
Stacktrace:
```
Executing [/Users/rsvoboda/git/quarkus-quickstarts/using-vertx/target/using-vertx-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2019-08-29 13:10:52,269 ERROR [io.qua.ver.run.VertxRecorder] (main) Cannot instantiate the MessageCodec class io.quarkus.vertx.runtime.GenericMessageCodec: java.lang.InstantiationException: Type `io.quarkus.vertx.runtime.GenericMessageCodec` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
    at java.lang.Class.newInstance(DynamicHub.java:770)
    at io.quarkus.vertx.runtime.VertxRecorder.registerCodec(VertxRecorder.java:342)
    at io.quarkus.vertx.runtime.VertxRecorder.registerCodecs(VertxRecorder.java:335)
    at io.quarkus.vertx.runtime.VertxRecorder.configureVertx(VertxRecorder.java:52)
    at io.quarkus.deployment.steps.VertxProcessor$build15.deploy_0(VertxProcessor$build15.zig:196)
    at io.quarkus.deployment.steps.VertxProcessor$build15.deploy(VertxProcessor$build15.zig:36)
    at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:165)
    at io.quarkus.runtime.Application.start(Application.java:91)
    at io.quarkus.runtime.Application.run(Application.java:204)
    at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)

2019-08-29 13:10:52,272 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.015s. Listening on: http://0.0.0.0:8081
2019-08-29 13:10:52,272 INFO  [io.quarkus] (main) Installed features: [cdi, reactive-pg-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-reactive-streams-operators, vertx, vertx-web]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.882 s - in org.acme.vertx.JsonEndpointIT
[INFO] Running org.acme.vertx.NativeFruitsEndpointIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.acme.vertx.NativeFruitsEndpointIT
[INFO] Running org.acme.vertx.GreetingResourceIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.acme.vertx.GreetingResourceIT
[INFO] Running org.acme.vertx.ResourceUsingWebClientIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.acme.vertx.ResourceUsingWebClientIT
[INFO] Running org.acme.vertx.EventResourceIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.352 s - in org.acme.vertx.EventResourceIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by rsvoboda** [comment]
@stuartwdouglas / @cescoffier  / @gsmet
