### ISSUE TITLE
microprofile-fault-tolerance fails in NATIVE mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#267]
microprofile-fault-tolerance fails in NATIVE mode

Compilation of the binary executable fails with `Caused by: java.lang.ClassNotFoundException: io.smallrye.context.propagators.rxjava2.RxJava2ContextPropagator`

Probably the same problem as in https://github.com/quarkusio/quarkus/issues/3737

@gsmet fyi

**Comment by gsmet** [comment]
I just tried it with fresh master and it worked.

I ran `mvn clean install -Dnative` and the native test passes. Do I need to do something special?

**Comment by rsvoboda** [comment]
I still see it with latest master
patebin: https://paste.fedoraproject.org/paste/X9GBa42~DwGP6trisT7Usw

```
uname -a
Darwin RS 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 ```
```
mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /Users/rsvoboda/.sdkman/candidates/java/19.2.0-grl/jre
Default locale: en_CZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```
```
env | grep GRAAL
GRAALVM_HOME=/Users/rsvoboda/.sdkman/candidates/java/19.2.0-grl
```

**Comment by rsvoboda** [comment]
On CI there is the failure too
https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=6674
Build quickstarts - dev Started: 8/29/2019, 10:22:20 PM 

```
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ microprofile-fault-tolerance ---
[INFO] Building jar: /home/vsts/work/1/s/microprofile-fault-tolerance/target/microprofile-fault-tolerance-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ microprofile-fault-tolerance ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 830ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /home/vsts/work/1/s/microprofile-fault-tolerance/target/microprofile-fault-tolerance-1.0-SNAPSHOT-runner.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (default) @ microprofile-fault-tolerance ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /home/vsts/work/1/s/graalvm/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Drx.unsafe-disable=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar microprofile-fault-tolerance-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[microprofile-fault-tolerance-1.0-SNAPSHOT-runner:26700]    classlist:   9,734.79 ms
[microprofile-fault-tolerance-1.0-SNAPSHOT-runner:26700]        (cap):   1,265.28 ms
[microprofile-fault-tolerance-1.0-SNAPSHOT-runner:26700]        setup:   3,177.17 ms
22:02:29,159 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
[microprofile-fault-tolerance-1.0-SNAPSHOT-runner:26700]     analysis:  21,744.58 ms
Printing call tree to /home/vsts/work/1/s/microprofile-fault-tolerance/target/reports/call_tree_microprofile-fault-tolerance-1.0-SNAPSHOT-runner_20190829_220250.txt
Printing list of used classes to /home/vsts/work/1/s/microprofile-fault-tolerance/target/reports/used_classes_microprofile-fault-tolerance-1.0-SNAPSHOT-runner_20190829_220251.txt
Printing list of used packages to /home/vsts/work/1/s/microprofile-fault-tolerance/target/reports/used_packages_microprofile-fault-tolerance-1.0-SNAPSHOT-runner_20190829_220251.txt
Error: Class initialization failed: io.quarkus.runner.ApplicationImpl24
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization failed: io.quarkus.runner.ApplicationImpl24
Detailed message:

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:219)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization failed: io.quarkus.runner.ApplicationImpl24
Detailed message:

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:564)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:684)
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:129)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:357)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:92)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:120)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:179)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:263)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:154)
	at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4229)
	at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4472)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5260)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:214)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:333)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:509)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl24.<clinit>(ApplicationImpl24.zig:170)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: io/smallrye/context/propagators/rxjava2/RxJava2ContextPropagator
	at io.quarkus.deployment.steps.SmallRyeContextPropagationProcessor$buildStatic483.deploy_0(SmallRyeContextPropagationProcessor$buildStatic483.zig:173)
	at io.quarkus.deployment.steps.SmallRyeContextPropagationProcessor$buildStatic483.deploy(SmallRyeContextPropagationProcessor$buildStatic483.zig:36)
	at io.quarkus.runner.ApplicationImpl24.<clinit>(ApplicationImpl24.zig:92)
	... 34 more
Caused by: java.lang.ClassNotFoundException: io.smallrye.context.propagators.rxjava2.RxJava2ContextPropagator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```

**Comment by rsvoboda** [comment]
I tried to start from empty local repo, built quarkus, executed the quickstart and it failed too.

**Comment by cescoffier** [comment]
It's been fixed.
