### ISSUE TITLE
JWT-security has errors when used with opentracing extension.

### ISSUE THREAD

**Issue by sean-scott-lr** [quarkusio/quarkus-quickstarts#369]
1) Follow the security-jwt guide [link](https://quarkus.io/guides/security-jwt )
2) Add opentracing extension ( add to pom.xml )
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-opentracing</artifactId>
    </dependency> 
```
3) Send a GET request to `http://localhost:8080/secured/roles-allowed` with no Authorization Header ( or with a bogus value for the Bearer token )
4) Observe log message

```
Caused by: java.io.IOException: UT000034: Stream is closed
        at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:126)
        at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:115)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletResponseWrapper$DeferredOutputStream.write(HttpServletResponseWrapper.java:39)
        at org.jboss.resteasy.util.CommitHeaderOutputStream.write(CommitHeaderOutputStream.java:64)
        at org.jboss.resteasy.plugins.providers.StringTextStar.writeTo(StringTextStar.java:65)
        at org.jboss.resteasy.plugins.providers.StringTextStar.writeTo(StringTextStar.java:24)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:193)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:64)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:155)
        at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:156)
        at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
        at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:232)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:97)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:70)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:217)
        ... 57 more
```

**Comment by sean-scott-lr** [comment]
Version 1.0.0.CR1

**Comment by sberyozkin** [comment]
@sean-scott-lr @cescoffier `quarkus-smallrye-jwt` works with Vertx HTTP, right ? Just noticed the Undertow exception

**Comment by cescoffier** [comment]
You can still add quarkus-undertow as a dependency, and deploy your servlets.

**Comment by sberyozkin** [comment]
@cescoffier thanks, but here we have a JAX-RS app. Should the fix be about removing [this dependency](https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-opentracing/runtime/pom.xml#L47) ? Otherwise I guess it has to be excluded in this case in the demo ?

**Comment by sberyozkin** [comment]
I will try to exclude

**Comment by sberyozkin** [comment]
Going to open a quarkus issue

**Comment by sean-scott-lr** [comment]
@sberyozkin Correct, I am not trying to use servlets or undertow. ( I have not added quarkus-undertow  as a dependency)  I am just using JAX-RS.

**Comment by sberyozkin** [comment]
@sean-scott-lr can you please exclude `quarkus-undertow` from `quarkus-smallrye-opentracing` ? 
I'm getting
```
Caused by: java.lang.NoClassDefFoundError: io/quarkus/undertow/runtime/UndertowDeploymentRecorder
```
But the build itself passes when I remove this dependency in Quarkus master

**Comment by sean-scott-lr** [comment]
I tried changing the dependency in my pom.xml to
`    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-opentracing</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-undertow</artifactId>
        </exclusion>
      </exclusions>
    </dependency>`

Still see this in the logs.

`Caused by: java.io.IOException: UT000034: Stream is closed
        at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:126)
        at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:115)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletResponseWrapper$DeferredOutputStream.write(HttpServletResponseWrapper.java:39)
        at org.jboss.resteasy.util.CommitHeaderOutputStream.write(CommitHeaderOutputStream.java:64)
        at org.jboss.resteasy.plugins.providers.StringTextStar.writeTo(StringTextStar.java:66)
        at org.jboss.resteasy.plugins.providers.StringTextStar.writeTo(StringTextStar.java:24)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:193)
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:64)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:155)
        at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:156)
        at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
        at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:232)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:97)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:70)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:217)
        ... 57 more`

**Comment by sberyozkin** [comment]
Opened https://github.com/quarkusio/quarkus/issues/5419
