### ISSUE TITLE
ElasticSearch quickstart broken

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#373]
```[INFO] Running org.acme.hibernate.search.elasticsearch.service.LibraryResourceTest
2019-11-13 05:16:24,992 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.hibernate-search.elasticsearch.automatic-indexing.synchronization.strategy" provided
2019-11-13 05:16:29,135 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Warning Code: 0, SQLState: 00000
2019-11-13 05:16:29,135 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) relation "book" does not exist, skipping
2019-11-13 05:16:29,136 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Warning Code: 0, SQLState: 00000
2019-11-13 05:16:29,136 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) table "author" does not exist, skipping
2019-11-13 05:16:29,137 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Warning Code: 0, SQLState: 00000
2019-11-13 05:16:29,137 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) table "book" does not exist, skipping
2019-11-13 05:16:29,138 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Warning Code: 0, SQLState: 00000
2019-11-13 05:16:29,138 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) sequence "hibernate_sequence" does not exist, skipping
05:16:31,569 (elasticsearch[hpc-dl360a-01.mw.lab.eng.bos.redhat.com][search][T#2])  WARN IndexShard:157 - onQueryPhase listener [org.elasticsearch.index.SearchSlowLog@1a39193a] failed
java.lang.RuntimeException: Internal error: total len assumed to be 2, copied 0 bytes
	at com.fasterxml.jackson.core.util.ByteArrayBuilder.toByteArray(ByteArrayBuilder.java:134) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.util.ByteArrayBuilder.completeAndCoalesce(ByteArrayBuilder.java:179) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.io.JsonStringEncoder.quoteAsUTF8(JsonStringEncoder.java:283) ~[jackson-core-2.8.11.jar:2.8.11]
	at org.elasticsearch.common.logging.ESLogMessage.escapeJson(ESLogMessage.java:49) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.index.SearchSlowLog$SearchSlowLogMessage.prepareMap(SearchSlowLog.java:174) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.index.SearchSlowLog$SearchSlowLogMessage.<init>(SearchSlowLog.java:159) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.index.SearchSlowLog.onQueryPhase(SearchSlowLog.java:139) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.index.shard.SearchOperationListener$CompositeListener.onQueryPhase(SearchOperationListener.java:155) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.search.SearchService$SearchOperationListenerExecutor.close(SearchService.java:1130) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:362) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.search.SearchService.lambda$rewriteShardRequest$7(SearchService.java:1043) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:45) [elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.0.jar:7.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
2019-11-13 05:16:31,690 INFO  [org.hib.sea.map.orm.mas.mon.imp.SimpleIndexingProgressMonitor] (Hibernate Search: Mass indexing - Author - ID loading - 1) HSEARCH000027: Going to reindex 2 entities
2019-11-13 05:16:31,939 INFO  [org.hib.sea.map.orm.mas.mon.imp.SimpleIndexingProgressMonitor] (Hibernate Search: Mass indexing - Book - ID loading - 1) HSEARCH000027: Going to reindex 13 entities
2019-11-13 05:16:32,460 INFO  [org.hib.sea.map.orm.mas.mon.imp.SimpleIndexingProgressMonitor] (main) HSEARCH000028: Reindexed 15 entities
2019-11-13 05:16:32,462 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 5.564s. Listening on: http://0.0.0.0:8081
2019-11-13 05:16:32,463 INFO  [io.quarkus] (main) Profile test activated. 
2019-11-13 05:16:32,463 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, hibernate-search-elasticsearch, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.339 s <<< FAILURE! - in org.acme.hibernate.search.elasticsearch.service.LibraryResourceTest
[ERROR] testLibrary  Time elapsed: 2.733 s  <<< FAILURE!
java.lang.AssertionError: 
2 expectations failed.
JSON path firstName doesn't match.
Expected: iterable containing ["David"]
  Actual: []

JSON path lastName doesn't match.
Expected: iterable containing ["Wrong"]
  Actual: []

	at org.acme.hibernate.search.elasticsearch.service.LibraryResourceTest.testLibrary(LibraryResourceTest.java:58)

2019-11-13 05:16:35,259 INFO  [io.quarkus] (main) Quarkus stopped in 0.049s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LibraryResourceTest.testLibrary:58 2 expectations failed.
JSON path firstName doesn't match.
Expected: iterable containing ["David"]
  Actual: []

JSON path lastName doesn't match.
Expected: iterable containing ["Wrong"]
  Actual: []

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by gsmet** [comment]
Well, maybe people shouldn't merge PRs on components I'm responsible of :).

https://github.com/quarkusio/quarkus-quickstarts/pull/359 hasn't been merged while the core repo PR has been merged, thus the issue.
