### ISSUE TITLE
Spring Web with Kubernetes fails to build native image

### ISSUE THREAD

**Issue by jstakun** [quarkusio/quarkus-quickstarts#398]
Hello

I've added to spring-web-quickstart example Kubernetes client dependency and added simple test api endpoint:

package org.acme.spring.web;

import java.util.Hashtable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import io.fabric8.kubernetes.api.model.Pod;
import io.fabric8.kubernetes.client.KubernetesClient;
import javax.inject.Inject;

@RestController
public class TestAPI {
	@Inject
	KubernetesClient client;

	@RequestMapping("/kube")
	public Hashtable getPlatformObjects() {
		Hashtable hashtable = new Hashtable<>();		
		for (Pod currPod : client.pods().list().getItems()) {
			hashtable.put(currPod.getMetadata().getUid(), currPod.getMetadata().getName());
		}
		return hashtable;
	}
}

This runs fine with ./mvn quarkus:dev

But fails to build native image with ./mvnw clean package -Pnative:

[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM

[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /usr/local/graalvm-ce-19.2.1/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar spring-web-quickstart-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace spring-web-quickstart-1.0-SNAPSHOT-runner

[spring-web-quickstart-1.0-SNAPSHOT-runner:2739]    classlist:  14,115.02 ms

[spring-web-quickstart-1.0-SNAPSHOT-runner:2739]        (cap):   1,401.67 ms

[spring-web-quickstart-1.0-SNAPSHOT-runner:2739]        setup:   3,554.84 ms

17:07:07,769 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final

[DEBUG] [org.jboss.threads] Thread "Thread[build-14,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-18,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-4,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-13,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-10,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-11,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-3,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-7,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-15,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-19,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-9,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-1,5,build group]" exiting

Error: Image build request failed with exit status 137

[DEBUG] [io.quarkus.builder] Finished step "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build" in 131480 ms

[DEBUG] [io.quarkus.builder] Dependency of "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#result" finished; 0 remaining

[DEBUG] [io.quarkus.builder] Starting step "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#result"

[DEBUG] [io.quarkus.builder] Finished step "io.quarkus.deployment.pkg.steps.NativeImageBuildStep#result" in 1 ms

[DEBUG] [io.quarkus.builder] End step completed; 0 remaining

[DEBUG] [org.jboss.threads] Thread "Thread[build-12,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-6,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-20,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-2,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-17,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-5,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-8,5,build group]" exiting

[DEBUG] [org.jboss.threads] Thread "Thread[build-16,5,build group]" exiting

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  02:22 min

[INFO] Finished at: 2019-12-10T17:08:55Z

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.0.1.Final:native-image (default) on project spring-web-quickstart: Failed to generate a native image: Failed to augment application classes: Build failure: Build failed due to errors

[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image

[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:289)

[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)

[ERROR] 	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)

[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)

[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)

[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)

[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)

[ERROR] 	at java.lang.Thread.run(Thread.java:748)

[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

[ERROR] Caused by: java.lang.RuntimeException: Image generation failed

[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:278)

[ERROR] 	... 12 more

[ERROR] -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.0.1.Final:native-image (default) on project spring-web-quickstart: Failed to generate a native image

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)

    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:498)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to generate a native image

    at io.quarkus.maven.NativeImageMojo.execute (NativeImageMojo.java:299)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)

    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:498)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

Caused by: io.quarkus.creator.AppCreatorException: Failed to augment application classes

    at io.quarkus.creator.phase.augment.AugmentTask.run (AugmentTask.java:190)

    at io.quarkus.creator.phase.augment.AugmentTask.run (AugmentTask.java:48)

    at io.quarkus.creator.CuratedApplicationCreator.runTask (CuratedApplicationCreator.java:139)

    at io.quarkus.maven.NativeImageMojo.execute (NativeImageMojo.java:297)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)

    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:498)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors

	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image

	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:289)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)

	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)

	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)

	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)

	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)

	at java.lang.Thread.run(Thread.java:748)

	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

Caused by: java.lang.RuntimeException: Image generation failed

	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:278)

	... 12 more

 

    at io.quarkus.builder.Execution.run (Execution.java:108)

    at io.quarkus.builder.BuildExecutionBuilder.execute (BuildExecutionBuilder.java:121)

    at io.quarkus.deployment.QuarkusAugmentor.run (QuarkusAugmentor.java:130)

    at io.quarkus.creator.phase.augment.AugmentTask.run (AugmentTask.java:181)

    at io.quarkus.creator.phase.augment.AugmentTask.run (AugmentTask.java:48)

    at io.quarkus.creator.CuratedApplicationCreator.runTask (CuratedApplicationCreator.java:139)

    at io.quarkus.maven.NativeImageMojo.execute (NativeImageMojo.java:297)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)

    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)

    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)

    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)

    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)

    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)

    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:498)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

Caused by: java.lang.RuntimeException: Failed to build native image

    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build (NativeImageBuildStep.java:289)

    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:498)

    at io.quarkus.deployment.ExtensionLoader$1.execute (ExtensionLoader.java:941)

    at io.quarkus.builder.BuildContext.run (BuildContext.java:415)

    at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)

    at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:2011)

    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1535)

    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1426)

    at java.lang.Thread.run (Thread.java:748)

    at org.jboss.threads.JBossThread.run (JBossThread.java:479)

Caused by: java.lang.RuntimeException: Image generation failed

    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build (NativeImageBuildStep.java:278)

    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

    at java.lang.reflect.Method.invoke (Method.java:498)

    at io.quarkus.deployment.ExtensionLoader$1.execute (ExtensionLoader.java:941)

    at io.quarkus.builder.BuildContext.run (BuildContext.java:415)

    at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)

    at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:2011)

    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1535)

    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1426)

    at java.lang.Thread.run (Thread.java:748)

    at org.jboss.threads.JBossThread.run (JBossThread.java:479)

**Comment by gsmet** [comment]
Exit code 137 often means not enough memory to build the native image.

Time to close some browser tabs :).

**Comment by jstakun** [comment]
Thanks! Increasing -Xmx for maven solved this issue
