### ISSUE TITLE
Importing sample realm config for keycloak is not possible

### ISSUE THREAD

**Issue by mhartwig** [quarkusio/quarkus-quickstarts#412]
Importing the keycloak sample config of [security-openid-connect-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-openid-connect-quickstart) fails with newest keycloak docker images, because the packaging format was changed.

```
10:54:55,966 WARN  [org.keycloak.services] (ServerService Thread Pool -- 72) KC-SERVICES0005: Unable to import realm quarkus from file /tmp/quarkus-realm.json.: java.lang.RuntimeException: Script upload is disabled
	at org.keycloak.keycloak-authz-policy-common@8.0.1//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.updatePolicy(JSPolicyProviderFactory.java:125)
	at org.keycloak.keycloak-authz-policy-common@8.0.1//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.onImport(JSPolicyProviderFactory.java:70)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2306)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:351)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.importPolicies(RepresentationToModel.java:2232)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2180)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.importAuthorizationSettings(RepresentationToModel.java:2127)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.lambda$importRealmAuthorizationSettings$0(RepresentationToModel.java:2105)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.importRealmAuthorizationSettings(RepresentationToModel.java:2103)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:456)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:506)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:451)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication.importRealm(KeycloakApplication.java:408)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication.importRealms(KeycloakApplication.java:384)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication.migrateAndBootstrap(KeycloakApplication.java:259)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:180)
	at org.keycloak.keycloak-server-spi-private@8.0.1//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:171)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication.init(KeycloakApplication.java:162)
	at org.keycloak.keycloak-services@8.0.1//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:143)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2784)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:364)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:277)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:89)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:119)
	at org.jboss.resteasy.resteasy-jaxrs@3.9.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:585)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
```

**Comment by gsmet** [comment]
@sberyozkin @pedroigor could you have a look at that one?

**Comment by mhartwig** [comment]
I updated the realm config with a working one: https://github.com/quarkusio/quarkus-quickstarts/pull/413

**Comment by gsmet** [comment]
The PR has been merged.
