### ISSUE TITLE
CDI is not working in Google Function

### ISSUE THREAD

**Issue by AbhideepChakravarty** [quarkusio/quarkus-quickstarts#641]
I followed the steps given in https://quarkus.io/guides/gcp-functions

But the injection if GreetingService is not happening and I am getting a NULL pointer exception at the line which makes a call to greetingService.hello().

Whats going wrong?

**Comment by loicmathieu** [comment]
Can you give me the `gcloud` command line you use to launch your function ?
I didn't test the Maven Google plugin yet, so I cannot help you with it.

**Comment by AbhideepChakravarty** [comment]
I didn't deploy in cloud. Tell me how can I first make it run in local
before deploying to cloud, with CDI working.

**Comment by loicmathieu** [comment]
So how do you test it ?

Do you follow our instructions to test your function locally via the invoker: https://quarkus.io/guides/gcp-functions#testing-locally

If CDI is not working, maybe it's because you directly invoke your function whereas you must invoke the `io.quarkus.gcp.functions.QuarkusHttpFunction` for Http function or the `io.quarkus.gcp.functions.QuarkusBackgroundFunction`. These are the Quarkus functions responsible to bootstrap Quarkus and its CDI containers, inject dependencies inside your function, and then delegate all calls to your functions.

**Comment by AbhideepChakravarty** [comment]
Hi,

My bad, I was actually invoking my function directly. But I tried invoking
Quarkus code. Here is the observation:

My POM:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.fastserve</groupId>
    <artifactId>quarkustest</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-google-cloud-functions</artifactId>
            <version>1.7.0.Final</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>1.7.0.Final</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <excludes>
                        <exclude>.google/</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                
                <groupId>com.google.cloud.functions</groupId>
                <artifactId>function-maven-plugin</artifactId>
                <version>0.9.4</version>
                <configuration>


<functionTarget>io.quarkus.gcp.functions.QuarkusBackgroundFunction</functionTarget>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>


No I am not using the google plugin to run your code.

Target folder:
PS C:\Users\Admin\Documents\NetBeansProjects\quarkustest> dir .\target\


    Directory: C:\Users\Admin\Documents\NetBeansProjects\quarkustest\target


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        25-Aug-20   6:54 AM                classes
d-----        25-Aug-20   6:54 AM                deployment
d-----        25-Aug-20   6:53 AM                generated-sources
d-----        25-Aug-20   6:53 AM                generated-test-sources
d-----        25-Aug-20   6:53 AM                maven-archiver
d-----        25-Aug-20   6:53 AM                maven-status
d-----        25-Aug-20   6:54 AM                test-classes
-a----        25-Aug-20   6:54 AM        4409586
quarkustest-1.0.0-SNAPSHOT-runner.jar
-a----        25-Aug-20   6:54 AM           4772
quarkustest-1.0.0-SNAPSHOT.jar.original


PS C:\Users\Admin\Documents\NetBeansProjects\quarkustest>


PS C:\Users\Admin\Documents\NetBeansProjects\quarkustest> dir



    Directory: C:\Users\Admin\Documents\NetBeansProjects\quarkustest


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        22-Aug-20   7:43 PM                src
d-----        25-Aug-20   6:54 AM                target
-a----        22-Aug-20   7:57 PM        5859015
java-function-invoker-1.0.0-beta1.jar
-a----        22-Aug-20   7:38 PM           1029 nb-configuration.xml
-a----        22-Aug-20   8:29 PM            811 nbactions.xml
-a----        25-Aug-20   6:47 AM           2575 pom.xml


PS C:\Users\Admin\Documents\NetBeansProjects\quarkustest> java -jar
java-function-invoker-1.0.0-beta1.jar --classpath
target/google-cloud-functions-1.0.0-SNAPSHOT-runner.jar --target
io.quarkus.gcp.functions.QuarkusBackgroundFunction

2020-08-25 06:57:50.378:INFO::main: Logging initialized @443ms to
org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.RuntimeException: Class
io.quarkus.gcp.functions.QuarkusBackgroundFunction does not exist or could
not be loaded
        at
com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:295)
        at
com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:140)
Caused by: java.lang.ClassNotFoundException:
io.quarkus.gcp.functions.QuarkusBackgroundFunction
        at
java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at
com.google.cloud.functions.invoker.runner.Invoker.loadFunctionClass(Invoker.java:336)
        at
com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:254)
        ... 1 more
PS C:\Users\Admin\Documents\NetBeansProjects\quarkustest>

Also note that your instruction says
google-cloud-functions-1.0-SNAPSHOT-runner.jar,
while the build generated google-cloud-functions-1.0.0-SNAPSHOT-runner.jar

Regards,
Abhideep

**Comment by loicmathieu** [comment]
You should use the generated runner jar inside your project: `quarkustest-1.0.0-SNAPSHOT-runner.jar`.
So the correct invoker URL should be
```
 java -jar java-function-invoker-1.0.0-beta1.jar \
  --classpath target/quarkustest-1.0.0-SNAPSHOT-runner.jar \
  --target io.quarkus.gcp.functions.QuarkusBackgroundFunction
```

I'll update the documentation to be more explicit ;)

**Comment by loicmathieu** [comment]
I create a small PR to add clarification to the guides: https://github.com/quarkusio/quarkus/pull/11677
Can I close this issue ?

**Comment by AbhideepChakravarty** [comment]
When I did maven clean install, it created the runner jar in the target
folder, then only I could add that in the classpath and used the function.

**Comment by loicmathieu** [comment]
Yes, I added this step in the PR quarkusio/quarkus#11677
You need to build the JAR that will contains your function class and all the needed Quarkus (and other librairies) classes
