### ISSUE TITLE
grpc-tls-quickstart fails to start due missing certificate configuration

### ISSUE THREAD

**Issue by vinicius-martinez** [quarkusio/quarkus-quickstarts#709]
Hi there,

When running grpc-tls-quickstart the following exception is raised:

`2020-11-11 15:51:32,499 INFO  [io.qua.grp.run.GrpcSslUtils] (Quarkus Main Thread) Disabling gRPC plain-text as the SSL certificate is configured
2020-11-11 15:51:32,533 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.nio.file.NoSuchFileException: src/main/resources/tls/server.pem
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at io.quarkus.grpc.runtime.GrpcSslUtils.getFileContent(GrpcSslUtils.java:135)
	at io.quarkus.grpc.runtime.GrpcSslUtils.createPemKeyCertOptions(GrpcSslUtils.java:144)
	at io.quarkus.grpc.runtime.GrpcSslUtils.applySslOptions(GrpcSslUtils.java:64)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$7.handle(GrpcServerRecorder.java:253)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$7.handle(GrpcServerRecorder.java:249)
	at io.vertx.grpc.VertxServerBuilder.useSsl(VertxServerBuilder.java:144)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.buildServer(GrpcServerRecorder.java:249)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.devModeStart(GrpcServerRecorder.java:141)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.initializeGrpcServer(GrpcServerRecorder.java:80)
	at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy_0(GrpcServerProcessor$build215158828.zig:94)
	at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy(GrpcServerProcessor$build215158828.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:587)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:95)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by vinicius-martinez** [comment]
Fixed by:

1. Create a **META-INF** directory under _src/main/resources;_
2. Move all contents from _tls_ to the new directory;
`.
├── META-INF
│   └── tls
│       ├── README.md
│       ├── ca-openssl.cnf
│       ├── ca.pem
│       ├── server-openssl.cnf
│       ├── server.key
│       └── server.pem
└── application.properties`
3. Update application.properties with the following content:
`quarkus.grpc.clients.hello.ssl.trust-store=META-INF/tls/ca.pem
quarkus.grpc.server.ssl.certificate=META-INF/tls/server.pem
quarkus.grpc.server.ssl.key=META-INF/tls/server.key`

**Comment by michalszynkiewicz** [comment]
The long story is that the client certificates work only when specified by a path to file. And while `src/main/resources/tls/...` is a proper path, it doesn't work for quarkus:dev (and won't for running the jar) because it won't be available.

I think the proper solution is to support reading the cert for the client from classpath (we already have it for the server). It would let us use `tls/ca.pem` as the path to client's trust store (we already can do `tls/server.pem` and `tls/server.key` for the other files)
