### ISSUE TITLE
Keycloak authorization tests failing in native

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-quickstarts#772]
/cc @sberyozkin 

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.security.keycloak.authorization.NativePolicyEnforcerIT
Executing [/home/runner/work/quarkus-quickstarts/quarkus-quickstarts/security-keycloak-authorization-quickstart/target/security-keycloak-authorization-quickstart-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/target/quarkus.log]
Feb 05, 2021 5:42:33 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:215)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:172)
	at java.net.URL.getURLStreamHandler(URL.java:71)
	at java.net.URL.<init>(URL.java:651)
	at java.net.URL.<init>(URL.java:541)
	at java.net.URL.<init>(URL.java:488)
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.makeRequest(OAuth2API.java:93)
	at io.vertx.ext.auth.oauth2.providers.OpenIDConnectAuth.discover(OpenIDConnectAuth.java:42)
	at io.vertx.ext.auth.oauth2.providers.KeycloakAuth.discover(KeycloakAuth.java:120)
	at io.quarkus.oidc.runtime.OidcRuntimeClient$6.accept(OidcRuntimeClient.java:151)
	at io.quarkus.oidc.runtime.OidcRuntimeClient$6.accept(OidcRuntimeClient.java:149)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:24)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:58)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:52)
```

**Comment by sberyozkin** [comment]
@gsmet Hi Guillaume, it looks new to me, the tests have run in the native mode for a while. See this commit:

https://github.com/quarkusio/quarkus-quickstarts/commit/381ecdcd73d0d0d4781fc8fe5cf3486479cdb6e5#diff-8906d3f595317042455b9a23e272183cc64a2747019a42d25f5278822debefbe

What is the right way to put those handlers back now ?

**Comment by sberyozkin** [comment]
something like this
```
quarkus.native.additional-build-args=-H:EnableURLProtocols=http\\,https
```
or under the native profile:
```
<properties>
                <quarkus.native.enable-all-security-services>true</quarkus.native.enable-all-security-services>
                <quarkus.native.enable-https-url-handler>true</quarkus.native.enable-https-url-handler>
</properties>
```
I'll fix it

**Comment by famod** [comment]
Sorry I missed that one when removing the `native-image` goal! I'll re-check that I did miss anything else.

**Comment by famod** [comment]
Unless there is a JNI config property (I couldn't find any), I haven't missed anything else.

**Comment by sberyozkin** [comment]
We can close it now I believe
