### ISSUE TITLE
gRPC (plain + tls) unit tests are broken in 1.13.2.Final

### ISSUE THREAD

**Issue by yuriy-larin-firstbridge** [quarkusio/quarkus-quickstarts#842]
gRPC unit tests are broken in both modules plain + tls
When I run tests (or do build) inside /grpc-plain-text-quickstart and /grpc-tls-quickstart modules they fails with errors like below.

1.
```
[INFO] Running io.quarkus.grpc.examples.hello.HelloWorldEndpointTest
2021-04-21 19:12:13,171 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-0) Registering gRPC reflection service
2021-04-21 19:12:13,314 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-1) gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
2021-04-21 19:12:13,373 INFO  [io.quarkus] (main) Quarkus 1.13.2.Final on JVM started in 2.905s. Listening on: http://localhost:8081
2021-04-21 19:12:13,373 INFO  [io.quarkus] (main) Profile test activated. 
2021-04-21 19:12:13,374 INFO  [io.quarkus] (main) Installed features: [cdi, grpc-client, grpc-server, mutiny, resteasy, resteasy-mutiny, smallrye-context-propagation, vertx]
2021-04-21 19:12:15,474 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello/blocking/neo failed, error id: 067c56b0-9d7a-4dfc-9826-0c8e9d5860f7-1: org.jboss.resteasy.spi.UnhandledException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
..........
```

2.
```
[INFO] Running io.quarkus.grpc.examples.hello.HelloWorldServiceTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.062 s <<< FAILURE! - in io.quarkus.grpc.examples.hello.HelloWorldServiceTest
[ERROR] io.quarkus.grpc.examples.hello.HelloWorldServiceTest.testHelloWorldServiceUsingBlockingStub  Time elapsed: 0.031 s  <<< ERROR!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.quarkus.grpc.examples.hello.HelloWorldServiceTest.testHelloWorldServiceUsingBlockingStub(HelloWorldServiceTest.java:40)
.............

```

**Comment by cescoffier** [comment]
Yes, the port is wrong.
Fortunately it's been already fixed upstream.
