### ISSUE TITLE
Using rest-client to @POST body fails with error RESTEASY003215

### ISSUE THREAD

**Issue by jeanabraham** [quarkusio/quarkus-quickstarts#863]
Hi,

I have a RESTEasy service to call an POST endpoint but it keeps failing with the below error. It works when I POST a String rather than a custom Pojo. Any ideas?

```
@RegisterRestClient
public interface KnativeEventDisplay {

    @POST
    @Path("/")
    
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    Response.Status trigger(@HeaderParam("ce-specversion") String specversion,
                            @HeaderParam("ce-source") String source,
                            @HeaderParam("ce-type") String type,
                            @HeaderParam("ce-id") String id,
                             MyPojo pojo);
    
}

```

```
public class MyPojo {

    private String foo;

	public String getFoo() {
		return foo;
	}

	public void setFoo(String foo) {
		this.foo = foo;
	}
}

```

```bash
Caused by: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/json type: com.acme.MyPojo
        at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:50)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:302)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:240)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:443)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:589)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:548)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:455)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:265)
        ... 51 more
```

**Comment by jeanabraham** [comment]
Closing this issue as the pom.xml was missing this dependency:

```
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-rest-client-jackson</artifactId>
    </dependency>
```
