### ISSUE TITLE
failed to build hibernate-reactive-panache-quickstart

### ISSUE THREAD

**Issue by drsarutobi8** [quarkusio/quarkus-quickstarts#901]
[drsarutobi@localhost hibernate-reactive-panache-quickstart]$ ./mvnw install

[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< org.acme:hibernate-reactive-panache-quickstart >-----------
[INFO] Building hibernate-reactive-panache-quickstart 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hibernate-reactive-panache-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ hibernate-reactive-panache-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/drsarutobi/projects/quarkus-quickstarts-main/hibernate-reactive-panache-quickstart/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hibernate-reactive-panache-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/drsarutobi/projects/quarkus-quickstarts-main/hibernate-reactive-panache-quickstart/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ hibernate-reactive-panache-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/drsarutobi/projects/quarkus-quickstarts-main/hibernate-reactive-panache-quickstart/target/test-classes
[INFO] 
[INFO] --- docker-maven-plugin:0.28.0:stop (docker-start) @ hibernate-reactive-panache-quickstart ---
[INFO] 
[INFO] --- docker-maven-plugin:0.28.0:start (docker-start) @ hibernate-reactive-panache-quickstart ---
[INFO] DOCKER> [postgres:10.5] "postgresql": Start container 59ea51df2c9b
[INFO] DOCKER> [postgres:10.5] "postgresql": Waiting for mapped ports [5432] on host localhost
[INFO] DOCKER> [postgres:10.5] "postgresql": Waited on tcp port '[localhost/127.0.0.1:5432]' 16 ms
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ hibernate-reactive-panache-quickstart ---
13:28:38.542 PostgreSQL:The files belonging to this database system will be owned by user "postgres".
13:28:38.542 PostgreSQL:This user must also own the server process.
13:28:38.542 PostgreSQL:
13:28:38.543 PostgreSQL:The database cluster will be initialized with locale "en_US.utf8".
13:28:38.543 PostgreSQL:The default database encoding has accordingly been set to "UTF8".
13:28:38.543 PostgreSQL:The default text search configuration will be set to "english".
13:28:38.543 PostgreSQL:
13:28:38.543 PostgreSQL:Data page checksums are disabled.
13:28:38.543 PostgreSQL:
13:28:38.543 PostgreSQL:fixing permissions on existing directory /var/lib/postgresql/data ... ok
13:28:38.543 PostgreSQL:creating subdirectories ... ok
13:28:38.556 PostgreSQL:selecting default max_connections ... 100
13:28:38.573 PostgreSQL:selecting default shared_buffers ... 128MB
13:28:38.573 PostgreSQL:selecting dynamic shared memory implementation ... posix
13:28:39.196 PostgreSQL:creating configuration files ... ok
13:28:39.436 PostgreSQL:running bootstrap script ... ok
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
13:28:40.273 PostgreSQL:performing post-bootstrap initialization ... ok
[INFO] Running org.acme.hibernate.orm.panache.FruitsEndpointTest
13:28:45.071 PostgreSQL:syncing data to disk ... ok
13:28:45.071 PostgreSQL:
13:28:45.072 PostgreSQL:WARNING: enabling "trust" authentication for local connections
13:28:45.072 PostgreSQL:You can change this by editing pg_hba.conf or using the option -A, or
13:28:45.072 PostgreSQL:--auth-local and --auth-host, the next time you run initdb.
13:28:45.072 PostgreSQL:
13:28:45.072 PostgreSQL:Success. You can now start the database server using:
13:28:45.072 PostgreSQL:
13:28:45.072 PostgreSQL:    pg_ctl -D /var/lib/postgresql/data -l logfile start
13:28:45.072 PostgreSQL:
13:28:45.358 PostgreSQL:waiting for server to start....2021-07-11 06:28:45.358 UTC [42] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
13:28:46.178 PostgreSQL:.2021-07-11 06:28:46.178 UTC [43] LOG:  database system was shut down at 2021-07-11 06:28:40 UTC
13:28:46.303 PostgreSQL:2021-07-11 06:28:46.303 UTC [42] LOG:  database system is ready to accept connections
13:28:46.392 PostgreSQL: done
13:28:46.393 PostgreSQL:server started
2021-07-11 13:28:52,143 INFO  [org.hib.rea.pro.imp.ReactiveIntegrator] (JPA Startup Thread: default-reactive) HRX000001: Hibernate Reactive Preview
2021-07-11 13:28:53,515 WARN  [org.hib.too.sch.int.exe.GenerationTargetToDatabase] (vert.x-eventloop-thread-0) HRX000021: DDL command failed [io.vertx.core.impl.NoStackTraceThrowable: Fail to read any response from the server, the underlying connection might get lost unexpectedly.]
2021-07-11 13:28:54,543 WARN  [org.hib.too.sch.int.exe.GenerationTargetToDatabase] (vert.x-eventloop-thread-0) HRX000021: DDL command failed [io.vertx.core.impl.NoStackTraceThrowable: Fail to read any response from the server, the underlying connection might get lost unexpectedly.]
2021-07-11 13:28:54,641 INFO  [io.quarkus] (main) Quarkus 2.0.1.Final on JVM started in 7.043s. Listening on: http://localhost:8081
2021-07-11 13:28:54,642 INFO  [io.quarkus] (main) Profile test activated. 
2021-07-11 13:28:54,642 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-orm, hibernate-reactive, hibernate-reactive-panache, reactive-pg-client, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/drsarutobi/.m2/repository/org/codehaus/groovy/groovy/3.0.8/groovy-3.0.8.jar) to constructor java.lang.AssertionError(java.lang.String)
[ERROR] WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
2021-07-11 13:28:57,921 ERROR [org.acm.hib.orm.pan.FruitResource] (vert.x-eventloop-thread-1) Failed to handle request: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
	[Exception 0] io.vertx.core.impl.NoStackTraceThrowable: Fail to read any response from the server, the underlying connection might get lost unexpectedly.
	[Exception 1] java.lang.IllegalStateException: session is currently connecting to database
	at io.smallrye.mutiny.groups.UniOnFailure.lambda$call$3(UniOnFailure.java:104)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnFailureTransform$UniOnFailureTransformProcessor.onFailure(UniOnFailureTransform.java:54)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:44)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromComplet

**Comment by drsarutobi8** [comment]
I copied the application.properties from hirbernate-reactive-quickstart (Non-panache version), and it seems to work just fine.

```
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# Reactive config
%prod.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost/quarkus_test
```

**Comment by gsmet** [comment]
@drsarutobi8 is it with the main branch or the development one?

@DavideD can you have a look at what's going on there?

Thanks!

**Comment by drsarutobi8** [comment]
I believe it is main branch

**Comment by DavideD** [comment]
I'm having a look at this

**Comment by DavideD** [comment]
I've created this PR: https://github.com/quarkusio/quarkus-quickstarts/pull/910
