### ISSUE TITLE
Test Entities with Panache

### ISSUE THREAD

**Issue by mhewedy** [quarkusio/quarkus-quickstarts#93]
I tried to test Entities as separate from service and resrouce layers, but I got `ContextNotActiveException`.

Here's the simple test case:

```
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class FruitTest {

    @Test
    public void testFindByName() {
        new Fruit("Apple").persist();
    }
}
```
And the stack trace:

```
INFO: XNIO version 3.6.5.Final
Mar 12, 2019 8:16:15 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.6.5.Final
Mar 12, 2019 8:16:15 AM io.quarkus.runtime.Timing printStartupTime
INFO: Quarkus 0.11.0 started in 1.597s. Listening on: http://127.0.0.1:8081
Mar 12, 2019 8:16:15 AM io.quarkus.runtime.Timing printStartupTime
INFO: Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb]

javax.enterprise.context.ContextNotActiveException
	at io.quarkus.arc.RequestContext.get(RequestContext.java:50)
	at io.quarkus.arc.RequestContext.get(RequestContext.java:64)
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.delegate(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:91)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.contains(TransactionScopedEntityManager.java:247)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.contains(ForwardingEntityManager.java:138)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.persist(JpaOperations.java:29)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.persist(JpaOperations.java:25)
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:37)
	at com.acme.hibernate.orm.panache.FruitTest.testFindByName(FruitTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Mar 12, 2019 8:16:16 AM io.quarkus.runtime.Timing printStopTime
INFO: Quarkus stopped in 0.014s
```
Here's the patch file
[#93_Test_Entities_with_Panache.patch.zip](https://github.com/quarkusio/quarkus-quickstarts/files/2955261/93_Test_Entities_with_Panache.patch.zip)

**Comment by mhewedy** [comment]
I noticed that, arc.RequestContext#destory and RequestContext#deactivate are being called too early. which is being called `UndertowDeploymentTemplate`

**Comment by gsmet** [comment]
@mhewedy could you share your project so that we can reproduce it?

**Comment by mhewedy** [comment]
Sorry for delay..

I have 2 test Classes;
One testing the service layer (and it works fine)
The other tests the persistence layer (via Panache directly) and it fails with the specified error above.

Somethings I have noticed that might be out of context:
1. I had to put @Transaction annotation on the Service Class method (even the read-only) so that the test case pass.
2. If I don't add the @Transactional on the method that updates the database I got nothing.. no exceptions and no data stored.
3. I was unable to rollback the database updates after each test method.

**Comment by mhewedy** [comment]
Any updates on this?

**Comment by gsmet** [comment]
@FroMage I think we should take a look at this one. Part of it might already been fixed but I'm not sure it's the case of all the issues described here.

**Comment by FroMage** [comment]
IIRC we're now setting up the Arc contexts properly in tests, so this should just work. Can you retry with the latest release please?

**Comment by cescoffier** [comment]
I believe it was fixed.
Please re-open otherwise.
