### ISSUE TITLE
[GraalVM 21.3.0.r17]  Class initialization of sun.lwawt.macosx.CInputMethod failed

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#989]
When using the Java 17 support of GraalVM 21.3.0, multiple quickstarts fail with: 

```
Error: Class initialization of sun.lwawt.macosx.CInputMethod failed. Use the option --initialize-at-run-time=sun.lwawt.macosx.CInputMethod to explicitly request delayed initialization of this class.
```

It would be interesting to try on other operating systems.

Impact quickstarts:

* awt-graphics-rest-quickstart
* liquibase-mongodb-quickstart (Fixed -https://github.com/quarkusio/quarkus/pull/21566)
* liquibase-quickstart (Fixed - https://github.com/quarkusio/quarkus/pull/21566)
* tika-quickstart

**Comment by Karm** [comment]
I haven't tested AWT extension on Mac. Given the nature of the extension, it will require porting.
You can assign this issue to me and I will see to either getting access to Mac HW and porting it or having someone who uses Mac to do it....

**Comment by cescoffier** [comment]
@Karm Thanks. 

I'm wondering why tikia and liquibase are using AWT?

**Comment by cescoffier** [comment]
BTW @Karm I did the test with GraalVM CE. It would be interesting to do the same with Mandrel.

**Comment by Karm** [comment]
> It would be interesting to do the same with Mandrel.

@cescoffier We don't build Mandrel on Mac OS.

> I'm wondering why tikia and liquibase are using AWT?

Anyone who needs to decode/encode any images, or to load/render anything fonts related needs AWT extension.
Even if you deserialize XML, you should be ready to decode images embedded in CDATA in XML documents...

So that is why things like Hibernate Validator pull AWT via JAXB.  Also Tika needs it to decode images etc. Not sure about liquidbase, but I think you get the gist.

**Comment by galderz** [comment]
I had a quick go at this. The issue is already present in the Tika ITs when running on mac. I tried to mark `sun.lwawt` package as runtime initialized but then it failed with:

```
2021-11-18 10:17:26,541 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /embedded/outerText failed, error id: f274554f-0631-4815-8754-68983ff44bdb-1: org.jboss.resteasy.spi.UnhandledException: java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:47)
	at java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.lang.System.loadLibrary(System.java:1989)
	at java.awt.Toolkit$2.run(Toolkit.java:1388)
	at java.awt.Toolkit$2.run(Toolkit.java:1386)
	at java.security.AccessController.doPrivileged(AccessController.java:87)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
	at java.awt.Toolkit.initStatic(Toolkit.java:1423)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1397)
	at java.awt.Rectangle.<clinit>(Rectangle.java:175)
	at org.apache.poi.hslf.blip.Metafile$Header.<init>(Metafile.java:53)
	at org.apache.poi.hslf.blip.EMF.getData(EMF.java:44)
	at org.apache.tika.parser.microsoft.HSLFExtractor.handleSlideEmbeddedPictures(HSLFExtractor.java:459)
	at org.apache.tika.parser.microsoft.HSLFExtractor.parse(HSLFExtractor.java:153)
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:178)
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:131)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at org.apache.tika.parser.RecursiveParserWrapper$EmbeddedParserDecorator.parse(RecursiveParserWrapper.java:376)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
	at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104)
	at org.apache.tika.extractor.EmbeddedDocumentUtil.parseEmbedded(EmbeddedDocumentUtil.java:220)
	at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedOfficeDoc(AbstractPOIFSExtractor.java:261)
	at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedOfficeDoc(AbstractPOIFSExtractor.java:146)
	at org.apache.tika.parser.microsoft.ExcelExtractor.parse(ExcelExtractor.java:179)
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:183)
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:131)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.RecursiveParserWrapper.parse(RecursiveParserWrapper.java:239)
	at io.quarkus.tika.TikaParser.parseStream(TikaParser.java:85)
	at io.quarkus.tika.TikaParser.parse(TikaParser.java:44)
	at io.quarkus.tika.TikaParser.parse(TikaParser.java:40)
	at io.quarkus.tika.TikaParser.parse(TikaParser.java:32)
	at io.quarkus.it.tika.TikaEmdeddedContentResource.extractOuterText(TikaEmdeddedContentResource.java:31)
```

There's a [long issue](https://github.com/oracle/graal/issues/2842) on this topic on the graal (which @zakkak has worked on before), but the current status appears to be that [macOS is not supported for this](https://github.com/oracle/graal/issues/2842#issuecomment-879620758). It says only Linux and Windows is supported, though the latter can break at times (e.g. https://github.com/oracle/graal/issues/3923)

**Comment by cescoffier** [comment]
Oh, thanks @galderz! That's very interesting. I believe we would need to indicate that these quickstarts do not work on Mac in native (liquibase, tika, and the AWT one). 

CC @maxandersen

**Comment by galderz** [comment]
I've tried with Java 11 on MacOS and the Tika quickstart shows the same issue (assuming the runtime package enhancement I mentioned above), so this is not Java 17 related. 

I didn't try `awt-graphics-rest-quickstart` but since it explicitly triggers awt features I'd expect to fail the same. 

However, I've just tried `liquibase-quickstart` and it doesn't fail. The dependency there comes via jaxb, so that would only trigger if an XML with an image would need to be parsed at runtime. In my local tests the quickstart works just fine.

**Comment by galderz** [comment]
@cescoffier Sent https://github.com/quarkusio/quarkus/pull/21566 to fix the `liquibase` quickstarts.

**Comment by cescoffier** [comment]
Thanks @galderz, I'm going to edit the main description to mention that the liquibase QS have been fixed.

**Comment by cescoffier** [comment]
Every QS has been fixed. Marking this issue as done.
